---
- name: Prepare K8s nodes
  hosts: all
  become: true
  roles:
    - common

- name: Configure Master node
  hosts: master
  become: true
  roles:
    - master

- name: Configure Worker nodes
  hosts: workers
  become: true
  roles:
    - worker
