prometheus:
  prometheusSpec:
    retention: 5d
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 512Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

grafana:
  adminPassword: "strong-password"
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: NodePort
    nodePort: 30000
  initChownData:
    enabled: false
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
