namespace: application

backend:
  image: ghcr.io/miracleqxz/k8s_project/backend
  tag: "bf61386ebbd27aef40641dfccc19819382341655"
  replicas: 2
  port: 5000
  resources:
    requests:
      memory: "100Mi"
    limits:
      memory: "200Mi"

frontend:
  image: ghcr.io/miracleqxz/k8s_project/web
  tag: "bf61386ebbd27aef40641dfccc19819382341655"
  replicas: 1
  port: 80
  nodePort: 30856
  resources:
    requests:
      memory: "100Mi"
    limits:
      memory: "200Mi"

mongodb:
  image: mongo
  tag: "latest"
  replicas: 1
  port: 27017
  storageSize: 1Gi

config:
  dbHost: mongodb
  dbPort: "27017"
  dbName: BANK
